AWSTemplateFormatVersion: "2010-09-09"
Description: Read-Only Lambda functions for Smart Office (List & Get Room Config)

Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
    AllowedValues: [Dev, Prod]

  DatabaseStackName:
    Type: String
    Description: "Nhap ten Stack DynamoDB (VD: SmartOffice-DynamoDB-Dev)"
    Default: "SmartOffice-DynamoDB-Dev"

Resources:
  # --- IAM ROLE (READ ONLY) ---
  SmartOfficeReadOnlyRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-ReadOnlyRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBReadPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - Fn::ImportValue: !Sub "${DatabaseStackName}-RoomConfigTableArn"

              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # --- LAMBDA FUNCTIONS ---

  # --- List Room Config ---
  ListRoomFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-ListRoom"
      Description: "List all room configurations"
      Runtime: python3.14
      Handler: ListRoom.lambda_handler
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt SmartOfficeReadOnlyRole.Arn
      Environment:
        Variables:
          ROOM_CONFIG_TABLE:
            Fn::ImportValue: !Sub "${DatabaseStackName}-RoomConfigTableName"
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return "ListRoom Infrastructure created..."

  ListRoomLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}-ListRoom"
      RetentionInDays: 3

  # --- Get Room Config ---
  GetRoomConfigFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-GetRoomConfig"
      Description: "Get specific room configuration"
      Runtime: python3.14
      Handler: GetRoomConfig.lambda_handler
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt SmartOfficeReadOnlyRole.Arn
      Environment:
        Variables:
          ROOM_CONFIG_TABLE:
            Fn::ImportValue: !Sub "${DatabaseStackName}-RoomConfigTableName"
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              return "GetRoomConfig Infrastructure created..."

  GetRoomConfigLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AWS::StackName}-GetRoomConfig"
      RetentionInDays: 3

Outputs:
  ListRoomFunctionArn:
    Description: ARN for ListRoom
    Value: !GetAtt ListRoomFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-ListRoomFunctionArn"

  GetRoomConfigFunctionArn:
    Description: ARN for GetRoomConfig
    Value: !GetAtt GetRoomConfigFunction.Arn
    Export:
      Name: !Sub "${AWS::StackName}-GetRoomConfigFunctionArn"
