AWSTemplateFormatVersion: "2010-09-09"
Description: API Gateway for Smart Office

Parameters:
  EnvironmentName:
    Type: String
    Default: Dev
    AllowedValues: [Dev, Prod]
  CrudLambdaStackName:
    Type: String
    Default: "SmartOffice-Crud-Lambda-Dev"
    Description: "SmartOffice-Crud-Lambda-Dev"

Resources:
  # --- API GATEWAY ---
  SmartOfficeApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: !Sub "${AWS::StackName}-Api"
      Description: "API Gateway for Smart Office"
      EndpointConfiguration:
        Types:
          - REGIONAL

  # /login
  LoginResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ParentId: !GetAtt SmartOfficeApi.RootResourceId
      PathPart: "login"

  # /logout
  LogoutResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ParentId: !GetAtt SmartOfficeApi.RootResourceId
      PathPart: "logout"

  # /forgot-password
  ForgotPasswordResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ParentId: !GetAtt SmartOfficeApi.RootResourceId
      PathPart: "forgot-password"

  # /confirm-forgot-password
  ConfirmForgotPasswordResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ParentId: !GetAtt SmartOfficeApi.RootResourceId
      PathPart: "confirm-forgot-password"

  # /profile-update
  ProfileUpdateResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ParentId: !GetAtt SmartOfficeApi.RootResourceId
      PathPart: "profile-update"

  # --- METHODS ---

  # --- PROFILE UPDATE ---
  ProfileUpdatePost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref ProfileUpdateResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri:
          Fn::Join:
            - ""
            - - "arn:aws:apigateway:"
              - !Ref "AWS::Region"
              - ":lambda:path/2015-03-31/functions/"
              - Fn::ImportValue: !Sub "${LambdaStackName}-ProfileUpdateFunctionArn"
              - "/invocations"

  # Permission for API Gatewayto call Lambda ProfileUpdate
  ProfileUpdatePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Fn::ImportValue: !Sub "${LambdaStackName}-ProfileUpdateFunctionArn"
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${SmartOfficeApi}/*/*/*"

  # CORS for Profile Update
  ProfileUpdateOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref ProfileUpdateResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
              "method.response.header.Access-Control-Allow-Methods": "'POST,OPTIONS'"
              "method.response.header.Access-Control-Allow-Origin": "'*'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Headers": true
            "method.response.header.Access-Control-Allow-Methods": true
            "method.response.header.Access-Control-Allow-Origin": true

  # --- LOGIN ---
  LoginPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref LoginResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: MOCK # <--- Mock return 200 OK, change to AWS_PROXY when finish all lambda
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  LoginOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref LoginResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Origin": "'*'"
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,Authorization'"
              "method.response.header.Access-Control-Allow-Methods": "'POST,OPTIONS'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin": true
            "method.response.header.Access-Control-Allow-Headers": true
            "method.response.header.Access-Control-Allow-Methods": true

  # 2. LOGOUT
  LogoutPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref LogoutResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  LogoutOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref LogoutResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Origin": "'*'"
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,Authorization'"
              "method.response.header.Access-Control-Allow-Methods": "'POST,OPTIONS'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin": true
            "method.response.header.Access-Control-Allow-Headers": true
            "method.response.header.Access-Control-Allow-Methods": true

  # --- FORGOT PASSWORD ---
  ForgotPasswordPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref ForgotPasswordResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  ForgotPasswordOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref ForgotPasswordResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Origin": "'*'"
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,Authorization'"
              "method.response.header.Access-Control-Allow-Methods": "'POST,OPTIONS'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin": true
            "method.response.header.Access-Control-Allow-Headers": true
            "method.response.header.Access-Control-Allow-Methods": true

  # --- CONFIRM FORGOT PASSWORD ---
  ConfirmForgotPasswordPost:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref ConfirmForgotPasswordResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
      MethodResponses:
        - StatusCode: 200

  ConfirmForgotPasswordOptions:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref SmartOfficeApi
      ResourceId: !Ref ConfirmForgotPasswordResource
      HttpMethod: OPTIONS
      AuthorizationType: NONE
      Integration:
        Type: MOCK
        RequestTemplates:
          application/json: '{"statusCode": 200}'
        IntegrationResponses:
          - StatusCode: 200
            ResponseParameters:
              "method.response.header.Access-Control-Allow-Origin": "'*'"
              "method.response.header.Access-Control-Allow-Headers": "'Content-Type,Authorization'"
              "method.response.header.Access-Control-Allow-Methods": "'POST,OPTIONS'"
      MethodResponses:
        - StatusCode: 200
          ResponseParameters:
            "method.response.header.Access-Control-Allow-Origin": true
            "method.response.header.Access-Control-Allow-Headers": true
            "method.response.header.Access-Control-Allow-Methods": true

  # --- DEPLOYMENT ---
  ApiDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - ProfileUpdatePost
      - LoginPost
      - LogoutPost
      - ForgotPasswordPost
      - ConfirmForgotPasswordPost
    Properties:
      RestApiId: !Ref SmartOfficeApi

  ApiStage:
    Type: AWS::ApiGateway::Stage
    Properties:
      StageName: !Ref EnvironmentName
      RestApiId: !Ref SmartOfficeApi
      DeploymentId: !Ref ApiDeployment

Outputs:
  ApiEndpoint:
    Description: "API Gateway Url"
    Value: !Sub "https://${SmartOfficeApi}.execute-api.${AWS::Region}.amazonaws.com/${EnvironmentName}"
    Export:
      Name: !Sub "${AWS::StackName}-ApiEndpoint"
